In [25]:
import numpy as np

<h2>Mean Absolute Error (MAE)</h2>

In [2]:
Y_predicted = np.array([1, 1 ,0, 0, 1])
Y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [15]:
def mae(Y_true, Y_predicted):   # This is the long method but we can do all this by just using numpy array 
    total_error = 0             # which is in the down cell
    for yt, yp in zip(Y_true, Y_predicted):
        total_error += abs(yt - yp)
    print("Total_error:", total_error)
    

In [16]:
mae(Y_true, Y_predicted)

Total_error: 2.5


In [23]:
np.mean(np.abs(Y_predicted - Y_true))
# Here Y_predicted - Y_true will give you the difference /

np.float64(0.5)

In [24]:
np.sum(np.abs(Y_predicted - Y_true))
# It will give you the total error

np.float64(2.5)

<h2>Log Loss or Binary Cross Entropy</h2>

In [29]:
np.log([0.00000000001])

array([-25.32843602])

In [30]:
epsilon = 1e-15

In [32]:
Y_predicted

array([1, 1, 0, 0, 1])

In [35]:
Y_predicted_new= [max(i,epsilon) for i in Y_predicted]
Y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [36]:
Y_predicted_new= [min(i,1-epsilon) for i in Y_predicted]
Y_predicted_new

[0.999999999999999,
 0.999999999999999,
 np.int64(0),
 np.int64(0),
 0.999999999999999]

In [37]:
Y_predicted_new = np.array(Y_predicted_new)
np.log(Y_predicted_new)

C:\Users\Hp\AppData\Local\Temp\ipykernel_5912\1547211217.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(Y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16,            -inf,            -inf,
       -9.99200722e-16])